# Generated by Django 4.2.4 on 2023-10-15 16:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_region', models.CharField(blank=True, max_length=155, null=True)),
                ('address_province', models.CharField(blank=True, max_length=155, null=True)),
                ('address_city', models.CharField(blank=True, max_length=155, null=True)),
                ('address_postal', models.CharField(blank=True, max_length=5, null=True)),
                ('address_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('address_street', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_first_name', models.CharField(max_length=155)),
                ('customer_last_name', models.CharField(max_length=100)),
                ('customer_phone_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('customer_username', models.CharField(max_length=10, unique=True)),
                ('customer_email', models.EmailField(max_length=255, unique=True)),
                ('customer_password', models.CharField(max_length=128)),
                ('customer_registered_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.customer')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.country'),
        ),
    ]
